# **260130/ml/02_사이킷런 살펴보기**

# **2-1. 들어가며**


## **들어가며**

안녕하세요 여러분. 이번 시간에는 사이킷런(scikit-learn)에 대해 알아보도록 하겠습니다.
사이킷런이란 무엇인지, 어떻게 활용할 수 있는지 살펴보고, 범주형과 수치형 데이터를 어떻게 전처리하는지 살펴보겠습니다.

## **학습목표**

- 범주형 데이터 전처리를 할 수 있다.
- 수치형 데이터 전처리를 할 수 있다.
- 머신러닝을 통해 예측할 수 있다.

## **오늘의 주제**

이번 시간에는 사이킷런에서 제공하는 데이터셋으로 머신러닝을 구현하고, 이후에는 공식문서를 어떻게 보는지도 설명해 드리도록 하겠습니다.

# **2-2. 사이킷런 활용하기**

## **데이터 불러오기**

In [ ]:
# 데이터 생성
import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data

          메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [ ]:
# 데이터 변경
data.loc[2,'원산지'] = '미국'

In [ ]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

# **2-3. 데이터 전처리: 범주형 데이터**

## **레이블 인코딩**

In [ ]:
# type확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   가격      9 non-null      int64
 1   호수      9 non-null      int64
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object
 4   살찔까요    9 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 492.0+ bytes

In [ ]:
# 레이블(label) 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['원산지'])
le.transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [ ]:
# fit_transform
# fit과 transform을 한번에!
le.fit_transform(df['원산지'])

array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [ ]:
# 데이터 변환
df['원산지'] = le.fit_transform(df['원산지'])
df

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

In [ ]:
# '살찔까요' 레이블인코딩
le = LabelEncoder()
df['살찔까요'] = le.fit_transform(df['살찔까요'])
df

      가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [ ]:
# 한번에 여러 개의 column을 인코딩하는 경우
# 활용할 데이터 선택 - 원본 데이터 불러오기
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
# 데이터가 object 타입인 column 선택 ['원산지', '살찔까요']

# 방법1
cols = ['원산지', '살찔까요']

# 방법2
cols = df.select_dtypes(include='object').columns
df

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
"""
for in 반복문
자료형에 담긴 자료들을 하나씩 꺼내고 싶을때 사용한다.
이렇게 반복문을 활용해서 실행을 하게 되면 컬럼이 아무리 많아도
반복문을 통해서 한번에 인코딩 할 수 있다.
"""
# 활용할 데이터 선택 - 원본 데이터 불러오기
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

# 한 번에 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# 인코딩 결과 확인
df

      가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [ ]:
"""
데이터 타입 자동 선택
"""
# object 타입선택 ['원산지', '살찔까요']
# cols = ['원산지', '살찔까요']
cols = df.select_dtypes(include='object').columns
df

      가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

## **원핫(one-hot) 인코딩**

In [ ]:
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

In [ ]:
# 원핫인코딩
# 데이터프레임을 입력받기 때문에 대괄호를 2번 써야 합니다. (df[['원산지']])
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)   # 기존 sparse=False 대신 수정, 사이킷런 버전 문제
cat = ohe.fit_transform(df[['원산지']])
cat

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
# 카테고리
ohe.categories_

[array(['국내산', '미국', '브라질'], dtype=object)]

In [ ]:
# 피처(컬럼)이름과 카테고리
ohe.get_feature_names_out()

array(['원산지_국내산', '원산지_미국', '원산지_브라질'], dtype=object)

In [ ]:
# 데이터프레임으로 변환
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

   원산지_국내산  원산지_미국  원산지_브라질
0      1.0     0.0      0.0
1      0.0     0.0      1.0
2      0.0     1.0      0.0
3      1.0     0.0      0.0
4      0.0     0.0      1.0
5      1.0     0.0      0.0
6      1.0     0.0      0.0
7      1.0     0.0      0.0
8      1.0     0.0      0.0

In [ ]:
# 데이터 프레임 합치기
df = pd.concat([df,df_cat],axis=1)
df

      가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0
5  13000  10  1400.0  국내산  yes      1.0     0.0      0.0
6  13000  10  1300.0  국내산  yes      1.0     0.0      0.0
7  12000  10  1000.0  국내산   no      1.0     0.0      0.0
8   9900  10  1000.0  국내산   no      1.0     0.0      0.0

In [ ]:
# 기존 컬럼 삭제
df = df.drop(['원산지'], axis=1)
df

      가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   no      1.0     0.0      0.0
1  15000  12  1500.0  yes      0.0     0.0      1.0
2  14000   9  1600.0  yes      0.0     1.0      0.0
3  14000   9  1800.0  yes      1.0     0.0      0.0
4  14000  11  1300.0  yes      0.0     0.0      1.0
5  13000  10  1400.0  yes      1.0     0.0      0.0
6  13000  10  1300.0  yes      1.0     0.0      0.0
7  12000  10  1000.0   no      1.0     0.0      0.0
8   9900  10  1000.0   no      1.0     0.0      0.0

원핫(one-hot) 인코딩(심화)

In [ ]:
# 여러 개 컬럼 한 번에 인코딩

# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df

"""
※TIP
Jupyter Notebook으로 학습을 진행하실 경우
코드 에러시 Jupyter Notebook내 하단에서 에러 위치를 확인 할수 있습니다.
또한 코드에 ctrl + / 로 주석처리를 하며 데이터 값, 옵션 값 등을 출력을 통해서
확인하면 빠르게 에러를 찾을 수 있습니다.
"""

'\n※TIP\nJupyter Notebook으로 학습을 진행하실 경우\n코드 에러시 Jupyter Notebook내 하단에서 에러 위치를 확인 할수 있습니다.\n또한 코드에 ctrl + / 로 주석처리를 하며 데이터 값, 옵션 값 등을 출력을 통해서 \n확인하면 빠르게 에러를 찾을 수 있습니다.\n'

In [ ]:
# 원핫인코딩
cols = df.select_dtypes(include='object').columns
ohe = OneHotEncoder(sparse_output=False)   # 기존 sparse=False 대신 수정, 사이킷런 버전 문제
cat = ohe.fit_transform(df[cols])
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out())
df_cat

   원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0      1.0     0.0      0.0      1.0       0.0
1      0.0     0.0      1.0      0.0       1.0
2      0.0     1.0      0.0      0.0       1.0
3      1.0     0.0      0.0      0.0       1.0
4      0.0     0.0      1.0      0.0       1.0
5      1.0     0.0      0.0      0.0       1.0
6      1.0     0.0      0.0      0.0       1.0
7      1.0     0.0      0.0      1.0       0.0
8      1.0     0.0      0.0      1.0       0.0

In [ ]:
# 데이터프레임 합치기
df = pd.concat([df, df_cat], axis=1)
df.head()

      가격  호수     칼로리  원산지 살찔까요  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0  국내산   no      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0  브라질  yes      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0   미국  yes      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0  국내산  yes      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0  브라질  yes      0.0     0.0      1.0      0.0       1.0

In [ ]:
# 컬럼 삭제
df = df.drop(cols, axis=1)
df

      가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

In [ ]:
# [TIP] 원핫인코딩: 판다스 활용
# 활용할 데이터 선택
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df.head()

      가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes

In [ ]:
# 판다스를 활용한 원핫 인코딩
df = pd.get_dummies(df)
df

      가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0     True   False    False     True     False
1  15000  12  1500.0    False   False     True    False      True
2  14000   9  1600.0    False    True    False    False      True
3  14000   9  1800.0     True   False    False    False      True
4  14000  11  1300.0    False   False     True    False      True
5  13000  10  1400.0     True   False    False    False      True
6  13000  10  1300.0     True   False    False    False      True
7  12000  10  1000.0     True   False    False     True     False
8   9900  10  1000.0     True   False    False     True     False

# **2-4. 데이터 전처리: 수치형 데이터**

## **표준화(평균0, 분산1 정규분포)_SS**

In [ ]:
# StandardScaler 불러오기
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [ ]:
# StandardScaler를 여러 변수에 사용
scaler = StandardScaler()
cols = ['가격', '호수', '칼로리']
scaler.fit_transform(df[cols])


df[cols] = scaler.fit_transform(df[cols])
df

         가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920     True   False    False     True     False
1  0.941508  1.940285  0.622376    False   False     True    False      True
2  0.340545 -1.333946  1.022475    False    True    False    False      True
3  0.340545 -1.333946  1.822672     True   False    False    False      True
4  0.340545  0.848875 -0.177822    False   False     True    False      True
5 -0.260417 -0.242536  0.222277     True   False    False    False      True
6 -0.260417 -0.242536 -0.177822     True   False    False    False      True
7 -0.861379 -0.242536 -1.378118     True   False    False     True     False
8 -2.123400 -0.242536 -1.378118     True   False    False     True     False

## **정규화 (데이터 범위 0~1)_MM**

In [ ]:
#MinMacScaler 불러오기
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
cols = ['가격', '호수', '칼로리']
scaler.fit_transform(df[cols])

df[cols] = scaler.fit_transform(df[cols])
df

         가격        호수    칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.000000  0.666667  0.250     True   False    False     True     False
1  0.836066  1.000000  0.625    False   False     True    False      True
2  0.672131  0.000000  0.750    False    True    False    False      True
3  0.672131  0.000000  1.000     True   False    False    False      True
4  0.672131  0.666667  0.375    False   False     True    False      True
5  0.508197  0.333333  0.500     True   False    False    False      True
6  0.508197  0.333333  0.375     True   False    False    False      True
7  0.344262  0.333333  0.000     True   False    False     True     False
8  0.000000  0.333333  0.000     True   False    False     True     False

# **2-5. 사이킷런에서 제공하는 데이터셋**

## **유방암 데이터**

In [ ]:
# 사이킷 런 데이터 불러오기
from sklearn.datasets import load_breast_cancer
dataset=load_breast_cancer()
dataset

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
# 피쳐이름 확인
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
# 타겟확인
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
#데이터 확인
dataset.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [ ]:
# 데이터프레임 형태로 변환
pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
# 타겟 추가하기
cancer_df['target'] = dataset.target
cancer_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
# 데이터셋 목록 확인 (load 로 시작하는 데이터셋은 불러올 수 있음)
import sklearn.datasets
sklearn.datasets.__all__

['clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_file',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_species_distributions',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_rcv1',
 'fetch_kddcup99',
 'fetch_openml',
 'get_data_home',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_breast_cancer',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_circles',
 'make_classification',
 'make_checkerboard',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll']

## **당뇨병 데이터**

In [ ]:
# 당뇨병 데이터 불러오기
from sklearn.datasets import load_diabetes
dataset_2=load_diabetes()
dataset_2

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
# 데이터프레임 형태로 변환
pd.DataFrame(data=dataset_2.data, columns=dataset_2.feature_names)
diabetes_df = pd.DataFrame(data=dataset_2.data, columns=dataset_2.feature_names)
diabetes_df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
# 타겟 추가하기
diabetes_df['target'] = dataset_2.target
diabetes_df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

# **2-6. 머신러닝**

## **의사결정나무 (DecisionTree)**

**학습(tr)/검증(te) 데이터 분리**

In [ ]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split
# X_train, X_test // y_train, y_test 분리
X_train, X_test, y_train, y_test = train_test_split(
    cancer_df.drop('target', axis=1), cancer_df['target'], test_size=0.3, random_state=1004)

In [ ]:
# train data 확인
X_train.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
350,11.660,17.07,73.70,421.0,0.07561,0.03630,0.008306,0.01162,0.1671,0.05731,...,13.28,19.74,83.61,542.5,0.09958,0.06476,0.03046,0.04262,0.2731,0.06825
384,13.280,13.72,85.79,541.8,0.08363,0.08575,0.050770,0.02864,0.1617,0.05594,...,14.24,17.37,96.59,623.7,0.11660,0.26850,0.28660,0.09173,0.2736,0.07320
7,13.710,20.83,90.20,577.9,0.11890,0.16450,0.093660,0.05985,0.2196,0.07451,...,17.06,28.14,110.60,897.0,0.16540,0.36820,0.26780,0.15560,0.3196,0.11510
557,9.423,27.88,59.26,271.3,0.08123,0.04971,0.000000,0.00000,0.1742,0.06059,...,10.49,34.24,66.50,330.6,0.10730,0.07158,0.00000,0.00000,0.2475,0.06969
49,13.490,22.30,86.91,561.0,0.08752,0.07698,0.047510,0.03384,0.1809,0.05718,...,15.15,31.82,99.00,698.8,0.11620,0.17110,0.22820,0.12820,0.2871,0.06917

In [ ]:
y_train.head()

350    1
384    1
7      0
557    1
49     1
Name: target, dtype: int64

In [ ]:
# 데이터 크기(분류 비율) 확인
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 30), (171, 30), (398,), (171,))

**분리데이터|를 머신러닝 모델에 학습**

In [ ]:
# 모델 호출 후 변수지정
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

# 학습
model.fit(X_train, y_train)

# 예측
pred = model.predict(X_test)
pred

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

**모델평가**

In [ ]:
# 정확도 accuracy_score(실제값, 예측값)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9064327485380117

## **선형회귀 (LinearRegression)**

**학습(tr)/검증(te) 데이터 분리**

In [ ]:
# 모듈 불러오기
from sklearn.model_selection import train_test_split
# X_train, X_test // y_train, y_test 분리
X_train, X_test, y_train, y_test = train_test_split(
    diabetes_df.drop('target', axis=1), diabetes_df['target'], test_size=0.3, random_state=1004)

In [ ]:
# train 데이터 확인
X_train.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
232,0.012648,0.050680,0.000261,-0.011420,0.039710,0.057245,-0.039719,0.056081,0.024055,0.032059
81,0.012648,0.050680,-0.022373,-0.029770,0.010815,0.028435,-0.021311,0.034309,-0.006081,-0.001078
227,0.067136,0.050680,-0.029918,0.057437,-0.000193,-0.015719,0.074412,-0.050564,-0.038460,0.007207
334,-0.060003,0.050680,-0.047163,-0.022885,-0.071743,-0.057681,-0.006584,-0.039493,-0.062917,-0.054925
83,-0.038207,-0.044642,0.009961,-0.046985,-0.059359,-0.052983,-0.010266,-0.039493,-0.015999,-0.042499

In [ ]:
y_train.head()

232    259.0
81      51.0
227    108.0
334     72.0
83     210.0
Name: target, dtype: float64

In [ ]:
# 데이터 크기(분류 비율) 확인
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((309, 10), (133, 10), (309,), (133,))

**분리데이터|를 머신러닝 모델에 학습**

In [ ]:
# 모델 호출 후 변수지정
from sklearn.linear_model import LinearRegression
model = LinearRegression()

# 학습
model.fit(X_train, y_train)

# 예측
pred = model.predict(X_test)
pred

array([128.42468606, 135.08774266, 154.78504343, 106.09306564,
       149.54478558, 165.32708009, 140.29166154, 167.9600165 ,
        69.44851384, 189.42811434, 144.98692247, 150.10700196,
       211.15983244, 108.59257071, 160.3856331 , 154.09855476,
       198.78116874, 101.16062264, 165.82852734, 196.03659567,
       147.16472505, 108.25668788, 207.27889551, 127.53191954,
       181.85997027, 228.49975565,  86.59589481, 155.35081963,
       182.49593133, 182.96390209, 207.63119699, 199.81134435,
       157.35809543,  61.82465786,  88.11634158,  95.75033061,
       134.03120864,  85.95903914, 177.69650387, 249.40014721,
       171.77206628, 204.71572412, 239.12149428,  89.24927278,
       244.20385113, 180.36498587, 161.10608699, 119.14846149,
       102.81815844, 153.35400825, 129.06743815, 208.80206598,
       107.93927973, 138.81355171, 166.04217088,  86.04455248,
       181.03094575, 117.97907348,  79.04947426, 127.20387612,
       194.05986421, 205.13463546, 233.84790901,  48.53871542,
       191.91330758, 126.17301722, 177.02687066, 145.4773665 ,
       142.43917722, 194.62775034, 121.36891561, 225.55242146,
       168.48807064,  88.14214752,  98.85877558,  75.1711283 ,
       244.27688759, 208.59789713, 163.92910281,  80.9058474 ,
       139.22234542, 183.73654227, 137.95481081, 119.40546543,
        87.86450559, 250.18732129, 133.89367128, 212.50828106,
       120.29112558, 188.09109508, 152.86043121, 208.53459919,
        93.50827475,  85.73981048, 112.98211117,  94.02452059,
       223.20824961, 124.37667641, 174.15276515, 206.9341477 ,
       109.03619979, 144.70485557,  83.62517483, 238.13216429,
       286.53698954, 135.49245966, 276.01107655, 117.56301055,
        85.55750781, 129.58770331, 106.44179834, 227.45717974,
       168.73559373, 104.04570771, 217.34657102, 161.55027088,
       226.95727237, 175.34674548, 145.94192866, 219.72261067,
        77.58172232, 126.38894167, 101.14367744, 173.50631434,
       137.35842139, 154.04979133, 146.58531953,  95.31923676,
       129.15889947, 117.11424948, 181.74918487,  68.73089256,
       175.84653715])

**평가 (Mean Squared Error,MSE)**
- 회귀모델에서는 MSE 를 성능지표로 많이 사용

In [ ]:
# 정확도 mean_squered_error(실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

3229.454787929743